# Generated by Django 4.2.10 on 2024-04-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceList', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listitem',
            options={'ordering': ['-productName']},
        ),
        migrations.AlterField(
            model_name='listitem',
            name='lastModified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
