# Generated by Django 4.2.10 on 2024-04-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priceList', '0002_alter_listitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listitem',
            options={'ordering': ['productName']},
        ),
    ]
