# Generated by Django 4.2.10 on 2024-04-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priceList', '0003_alter_listitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listitem',
            options={'ordering': ['price']},
        ),
    ]
